In [5]:
import numpy
import numpy as np
x = np.array([1,2,3,4,5])
y = np.array([9,10])
print(x)
print('the shape of x',x.shape)
print(y)
print('the shape of y',y.shape)

[1 2 3 4 5]
the shape of x (5,)
[ 9 10]
the shape of y (2,)


print ('the shape of x is', x.shape

In [3]:
print('the shape of x', x.shape)

the shape of x (5,)


In [4]:
import numpy
import numpy as np
prime = np.array([2,3,5,7])
print(prime)
print ('the shape of prime no is',prime.shape)


[2 3 5 7]
the shape of prime no is (4,)


In [7]:
z = np.array([[1,2], [3,4]])
print(z)

[[1 2]
 [3 4]]


In [8]:
print('the shape of z is',z.shape)

the shape of z is (2, 2)


In [9]:
w = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(w)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [10]:
print('the shape of w is',w.shape)

the shape of w is (4, 3)


In [14]:
A10 = np.arange[10]
print(A10)
print(A10.shape)

TypeError: 'builtin_function_or_method' object is not subscriptable

In [12]:
A10 = np.arange(10) #array is used to create arrays with values in a specific range


In [15]:
A10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
print(A10.shape)

(10,)


In [21]:
A10 = np.arange(10)
A10
print(A10.shape)

(10,)


In [29]:
import pandas as pd

data = [['AYO',10],['IMRAN',15],['CHUCKS',14]]

df = pd.DataFrame (data,columns = ['Names','Age'])

df

Names  Age
0     AYO   10
1   IMRAN   15
2  CHUCKS   14

In [31]:
import pandas as pd

In [33]:
Excel_df = pd.read_Excel ('desktop/nigeriapopulation.xlsx')
Excel_df

AttributeError: module 'pandas' has no attribute 'read_Excel'